=== Jobosc/depthai-shared/pipeline_builder/schema/Node.schema.json
{
    "$id": "https://lpb.luxonis.com/schema/Node.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Node schema",
    "description": "Node is a compute element with inputs and outputs",
    "type": "object",
    "required": ["name"],
    "definitions": {
        "Output": {
            "type": "object",
            "required": ["name", "datatype", "type"],
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": ["msender", "ssender"]
                },
                "possibleDatatypes": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["datatype"],
                        "properties": {
                            "datatype": {
                                "$ref": "Datatype.schema.json"
                            },
                            "descendants": {
                                "type": "boolean",
                                "default": false
                            }
                        }
                    }
                }
            }
        },
        "Input": {
          "type": "object",
          "required": ["name", "type", "acceptedDatatypes"],
          "properties": {
              "name": {
                  "type": "string"
              },
              "type": {
                  "type": "string",
                  "enum": ["sreceiver", "mreceiver"]
              },
              "acceptedDatatypes": {
                  "type": "array",
                  "items": {
                      "type": "object",
                      "required": ["datatype"],
                      "properties": {
                          "datatype": {
                              "$ref": "Datatype.schema.json"
                          },
                          "descendants": {
                              "type": "boolean",
                              "default": false
                          }
                      }
                  }
              }
          }
        }
    },
    "properties": {
        "name": {
            "type": "string"
        },
        "description": { 
          "type": "string"
        },
        "category": {
            "type": "string"
        },
        "properties": {
            "type": "string",
            "minLength": 1
        },
        "outputs": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Output"
            }
        },
        "inputs": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Input"
            }
        }
    }
  }

=== Jobosc/depthai-shared/pipeline_builder/nodes/XLinkOut/XLinkOut.json
{
	"name": "XLinkOut",
    "description": "XLinkIn transfers data from input to host",   
    "category": "IO",
    "properties": "XLinkOut.properties.schema.json",
    "inputs": [
        {
            "name": "in",
            "type": "sreceiver",
            "acceptedDatatypes": [
                {
                    "datatype": "PoBuf",
                    "descendants": true
                }
            ]
        }
    ]
}

=== Jobosc/depthai-shared/pipeline_builder/nodes/MyConsumer/MyConsumer.json
{
	"name": "MyConsumer",
    "description": "Sends message to output",
    "properties": "MyConsumer.properties.schema.json",
    "inputs": [
        {
            "name": "in",
            "type": "sreceiver",
            "acceptedDatatypes": [
                {
                    "datatype": "ImgFrame"
                }
            ]
        }
    ]
}
